# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wenqi Jiang
title: Big Data Engineer / Full-Stack Developer
email: jiangwenqi1995@gmail.com
website: jiangwenqi.info

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jiangwenqi1995
github_username: JiangWenqi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jiangwenqi1995
linkedin_username: jiangwenqi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Dev Community
    icon: fab fa-dev
    url: https://dev.to/jiangwenqi
  - title: BinarySearch
    icon: fas fa-code
    url: https://binarysearch.com/@/Vinci_1995
    # https://fontawesome.com/v5.15/icons?d=gallery&m=free
  - title: LeetCode
    icon: fas fa-terminal
    url: https://leetcode.com/JiangWenqi/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Wenqi. 

  I'm now studying a master's degree in Data Science at the Polytechnic University of Madrid (UPM) while working as an ontology engineer at Ontology Engineering Group (OEG).
  
  Prior to that, I worked in mainland China for over three years as a big data engineer and back end developer, so I have experience in handling Tbs data.

  I am most skilled in: <mark>Spark/Flink</mark> and <mark>Java/Scala</mark>.

  I've recently been working on <mark>Web 3</mark> in my spare time.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shenzhen Togic Software Technology Co.
        link: 51togic.com
        # link_text: boringcompany.com
        sub_title: Big Data Engineer
        caption: May 2019 - Aug 2021 · 2 yrs 4 mos
        quote: >
          Shenzhen Togic Software Technology Co., Ltd. was established in August 2010. The company focuses on home Internet TV clients, with its Togic application(similar to Netflix) and WEBOX(similar to Apple TV) delivering a simple, intuitive, and lightweight experience for family entertainment, quickly becoming the most popular app on TV systems. There are currently over 700,000 daily users on this platform, and near 9 million customers worldwide used these products.

        description: | # this will include new lines to allow paragraphs
          - Developed more than 70 offline statistics and generated reports in the context of business demands.
          - Completed migration of big data platform from Apache <mark> Hadoop</mark> to Cloudera Hadoop, and upgraded versions.
          - Restructured user log reception for higher throughput, robustness, and reliability.
          - Designed and developed data warehouse that saved over 80% storage space and eased the problem of small files on <mark>HDFS</mark>.
          - Improved performance and reduced hours of calculation time with <mark>Spark SQL</mark> on <mark>HIVE</mark>.

      - layout: left
        title: Beijing Webstudio Information Technology Co.
        link: wbdatavis.com
        # link_text: boringcompany.com
        sub_title: Back End Engineer
        caption: Jul 2018 - Apr 2019 · 10 mos
        quote: >
          Webstudio was founded in 2007 and focuses on quality-based and innovative development, providing data visualization analysis and presentation, as well as official website marketing solutions which span a wide range of business disciplines and application situations.
        description: | # this will include new lines to allow paragraphs
          - Developed big data visualization dashboards, generic reports backend interfaces for BI applications.
          - Expanded 16 data sources, like MySQL, SQL Server, MongoDB , etc.
          - Developed more than 30 data operators, such as summation, date conversion, string processing (<mark>Impala</mark> functions).
          - Built and maintained the big data platform.

      - layout: left
        title: Tsinghua University
        # link: wbdatavis.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: Feb 2018 - Jul 2018 · 6 mos
        quote: >
          Tsinghua University is a world-class research university in China.
        description: | # this will include new lines to allow paragraphs
          - Organized and annotated critical illness insurance documents for researching.
          - Trained a model by using <mark>GROBID</mark> to extract the logical structure of critical illness insurance documents.
          - Maintained <mark>NoSQL</mark> database, like MongoDB, Neo4j.
          - Completed the thesis.

  - title: Current Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: LOOM-LD
        # border: weak
        link: github.com/oeg-upm
        # link_text: Project Website
        caption: Jan 2022 - Present
        additional_links:
          - title: LOOM-LD
            icon: fab fa-github
            url: github.com/oeg-upm/loom-ld
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Student scholarship for the development of linking algorithms and graph linkers.
        description: | # this will include new lines to allow paragraphs
          Task to be developed:
          - Specification and development of link discovery algorithms;
          - Development of knowledge graph linker.

          Tags: <mark>Ontology</mark> <mark>SPARQL</mark> <mark>Apache Jena</mark> <mark>OAEI</mark>.

      - layout: right
        title: Dapp-Learning
        caption: Apr 2022 - Present
        link: github.com/Dapp-Learning-DAO
        # link_text: Project Website
        # caption: Jan 2022 - July 2022
        additional_links:
          - title: DAPP-LEARNING
            icon: fab fa-github
            url: github.com/Dapp-Learning-DAO/Dapp-Learning
        quote: >
          Definitive Guide for Decentralized-app(Dapp) Development on Blockchain.
          Step-by-step Dapp practice through actual projects.
        description: | # this will include new lines to allow paragraphs
          Task to be developed:
          - Contributions of various tasks to the repository; 
          - Translations of some basic tasks.

          Tags: <mark>Blockchain</mark> <mark>web3.0</mark> <mark>Solidity</mark> <mark>Ethereum</mark>.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Polytechnic University of Madrid
        caption: 2021 - 2022
        sub_title: MS Data Science
        quote: >
          The Polytechnic University of Madrid(UPM) is a public university was founded in 1971 as the result of merging different Technical Schools of Engineering and Architecture, originating mainly in the 18th century. 
          The Engineering and Architecture Schools of UPM have contributed significantly to the history of Spanish technology.
        # description: | # this will include new lines to allow paragraphs
        # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
      - layout: top-middle
        title: Beijing Information Science & Technology University
        caption: 2014 - 2018
        sub_title: BE Computer Science & Technology
        quote: >
          The Beijing Information Science and Technology University (BISTU) was founded in 2008 by merging the Beijing Machinery Industry Institute and the Beijing Information Engineering College, which are both created in the 19th century.
          It offers an excellent academic discipline system in information science and technology, and servers around 15,000 students from China and abroad.

        # description: | # this will include new lines to allow paragraphs
        # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data and software engineering, some of my other interests and hobbies are:
      - Powerlifting
      - Watching UFC fights
      - Traveling
      - CrossFit

      Look at this cool image  
      ![ufc](images/UFC_SHENZHEN.JPG "ufc")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
